name: makefile
on:
  push

run-name: ${{ github.actor }} is pushing new changes 🚀
jobs:
  Explore-GitHub-Actions:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Makefile
        run: make